### ISSUE TITLE
Update for CakePHP 4.x

### ISSUE THREAD

**Issue by tylerlazenby** [GrandFelix/cakephp-webpack#2]
It would be wonderful if this could be updated to CakePHP 4.x

**Comment by GrandFelix** [comment]
Will do it this weekend or next week. 👍

**Comment by marwain91** [comment]
Guess it didn't work out :-)

**Comment by GrandFelix** [comment]
🙈

**Comment by GrandFelix** [comment]
@marwain91 hi. Today I have updated this plugin for CakePHP 4. Tomorrow I will make a release. 💪

**Comment by GrandFelix** [comment]
1.0 version released
